### ISSUE TITLE
Missing 'ui-components.js.map' file 

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/ui-components#27]
I'm getting `FATAL` errors in console for some time now, informing me that `ui-components.js.map` is missing:

```log
[----] I, [2016-09-20T13:17:11.489026 #2775:2b1b6568b450]  INFO -- : Started GET "/assets/manageiq-ui-components/dist/js/ui-components.js.map" for ::1 at 2016-09-20 13:17:11 +0200
[----] F, [2016-09-20T13:17:11.540451 #2775:2b1b6568b450] FATAL -- :   
[----] F, [2016-09-20T13:17:11.540801 #2775:2b1b6568b450] FATAL -- : ActionController::RoutingError (No route matches [GET] "/assets/manageiq-ui-components/dist/js/ui-components.js.map"):
[----] F, [2016-09-20T13:17:11.540858 #2775:2b1b6568b450] FATAL -- :   
[----] F, [2016-09-20T13:17:11.540898 #2775:2b1b6568b450] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
[----] F, [2016-09-20T13:17:11.540934 #2775:2b1b6568b450] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[----] F, [2016-09-20T13:17:11.540980 #2775:2b1b6568b450] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
[----] F, [2016-09-20T13:17:11.541017 #2775:2b1b6568b450] FATAL -- : railties (5.0.0.1) lib/rails/rack/logger.rb:26:in `call'
[----] F, [2016-09-20T13:17:11.541053 #2775:2b1b6568b450] FATAL -- : request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
[----] F, [2016-09-20T13:17:11.541085 #2775:2b1b6568b450] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
[----] F, [2016-09-20T13:17:11.541116 #2775:2b1b6568b450] FATAL -- : rack (2.0.1) lib/rack/method_override.rb:22:in `call'
[----] F, [2016-09-20T13:17:11.541148 #2775:2b1b6568b450] FATAL -- : rack (2.0.1) lib/rack/runtime.rb:22:in `call'
[----] F, [2016-09-20T13:17:11.541178 #2775:2b1b6568b450] FATAL -- : activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[----] F, [2016-09-20T13:17:11.541210 #2775:2b1b6568b450] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
[----] F, [2016-09-20T13:17:11.541274 #2775:2b1b6568b450] FATAL -- : actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
[----] F, [2016-09-20T13:17:11.541314 #2775:2b1b6568b450] FATAL -- : rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
[----] F, [2016-09-20T13:17:11.541346 #2775:2b1b6568b450] FATAL -- : rack-mini-profiler (0.10.1) lib/mini_profiler/profiler.rb:171:in `call'
[----] F, [2016-09-20T13:17:11.541380 #2775:2b1b6568b450] FATAL -- : railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
[----] F, [2016-09-20T13:17:11.541411 #2775:2b1b6568b450] FATAL -- : puma (3.3.0) lib/puma/configuration.rb:224:in `call'
[----] F, [2016-09-20T13:17:11.541442 #2775:2b1b6568b450] FATAL -- : puma (3.3.0) lib/puma/server.rb:561:in `handle_request'
[----] F, [2016-09-20T13:17:11.541473 #2775:2b1b6568b450] FATAL -- : puma (3.3.0) lib/puma/server.rb:406:in `process_client'
[----] F, [2016-09-20T13:17:11.541503 #2775:2b1b6568b450] FATAL -- : puma (3.3.0) lib/puma/server.rb:271:in `block in run'
[----] F, [2016-09-20T13:17:11.541533 #2775:2b1b6568b450] FATAL -- : puma (3.3.0) lib/puma/thread_pool.rb:111:in `block in spawn_thread'
```

is there something, that can be done to fix this? :blush: @karelhala

**Comment by romanblanco** [comment]
@miq-bot assign @karelhala

**Comment by romanblanco** [comment]
@miq-bot add_label bug

**Comment by himdel** [comment]
@romanblanco Unrecognized command `assign`
@romanblanco Unrecognized command `add_label`
:trollface:

**Comment by romanblanco** [comment]
Oh... \*Sigh\*... Okay :smile:

**Comment by karelhala** [comment]
Well we need those maps in dev mode, but they should not be present in production mode. Not sure how to remove them when releasing new version.

**Comment by himdel** [comment]
@karelhala I think we *could* just put the map file in the bower package, lots of projects do that. The fact that we don't *need* it doesn't mean we can't package it..

**Comment by karelhala** [comment]
@himdel sounds good and reasonable. I'll update `.gitinore` and bower so the map will be present in bower package.
